name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    style:
        name: Styling
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
            - uses: JohnnyMorganz/stylua-action@v3.0.0
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  version: latest
                  args: --check .
